import "package:flutter/material.dart";

class AppColors {
  static const Color primary = Color(0xFF4A5FBD);
  static const Color primaryDark = Color(0xFF3839E6);
  static const Color primaryBlue = Color(0xFF0EA5E9);
  static const Color grey = Colors.grey;
  static const Color greyColor = Color(0xFF9E9E9E);
  static const Color greyShade100 = Color(0xFFF5F5F5);
  static const Color greyShade200 = Color(0xFFEBEBEB);
  static const Color greyShade250 = Color(0xFFE8E8E8);
  static const Color greyShade300 = Color(0xFFE0E0E0);

  static const Color gradientStart = Color(0xFF6A6DE3);
  static const Color gradientEnd = Color(0xFF3839E6);
  static const Color parentGradientStart = Color(0xFF5D7B72);
  static const Color parentGradientEnd = Color(0xFF719F92);
  static const Color royalBlue = Color(0xFF1565C0); // Colors.blue.shade800
  static const Color deepPurple = Color(0xFF4A148C); // Colors.purple.shade900
  static const Color mediumGrey = Color(0xFFE0E0E0); // Colors.grey.shade300
  static const Color mediumTealGreen = Color(0xFF55A689);
  static const Color mediumPurple = Color(0xFF8B5CF6);
  static const Color lightGreyShade100 = Color(
    0xFFF5F5F5,
  ); // Colors.grey.shade100
  static const Color deepBrown = Color(0xFF78350F);
  static const Color darkGrey = Color(0xFF424242);
  static const Color yellowShade = Color(0xFFFFF9E6);

  static const Color white = Colors.white;
  static const Color burntAmber = Color(0xFFB45309);
  static const Color black = Colors.black;
  static const Color red = Colors.red;
  static const Color vividBlue = Color(0xFF1828D4);
  static const Color blue = Colors.blue;
  static const Color burntOrange = Color(0xFFB7791F);
  static const Color orange = Colors.orange;
  static const Color blueColor = Color(0xFF2196F3);
  static const Color green = Colors.green;
  static const Color borderLine = Color(0xFFCBCBCB);
  static const Color fillColor = Color(0x5CD9D9D9);
  static const Color pendingStatusColor = Color(0xFFF4D633);
  static const Color breakColor = Color(0xFFE0FFE0);
  static const Color postBreakColor = Color(0xFFEBFFE5);
  static const Color approvedStatusColor = Color(0xff56f000);
  static const Color rejectedStatusColor = Color(0xffff3838);
  static const Color scaffoldBackground = Color(0xFFF5F5F5);
  static const Color softCyan = Color(0xFFCDE9E6);
  static const Color softYellow = Color(0xFFFFE29B);
  static const Color lavenderBackground = Color(0xFFEAF0FF);
  static const Color lightLavender = Color(0xFFE3D9FF);
  static const Color lavenderShade400 = Color(0xFFD4D1FF);
  static const Color lavenderShade800 = Color(0xFF9D8BFF);
  static const Color lightBlueShade = Color(0xFFE6F2F8);
  static const Color darkPurple = Color(0xFF8C61AE);
  static const Color lightCardBlue = Color(0xFFE9F1FF);
  static const Color lightPastelBlue = Color(0xFFD7EBFF);
  static const Color lightCardPurple = Color(0xFFF0EAFE);
  static const Color lightGrey = Color(0xFFDCDCDC);
  static const Color lightBlue = Color(0xFFE3F2FD);
  static const Color lightGreyBackground = Color(0xFFE9E9E9);
  static const Color lightPink = Color(0xFFFFE5E5);
  static const Color lightYellow = Color(0xFFFFF3C4);
  static const Color lightDivider = Color(0xFFECECEC);
  static const Color lightBlueShadeDarker = Color(0xFFD0E6F0);
  static const Color lightPurpleShade = Color(0xFFF2E6F8);
  static const Color lightGreenShade = Color(0xFFEAF8E6);
  static const Color lightYellowShade = Color(0xFFFFF4D8);
  static const Color lightPinkShade = Color(0xFFFFE6F0);
  static const Color mintGreenShade = Color(0xFFE6FFE6);
  static const Color coralRed = Color(0xFFFF6B6B);
  static const Color charcoalGrey = Color(0xFF303030);
  static const Color chipBlue = Color(0xFF4A90E2);
  static const Color chipPurple = Color(0xFF7B61FF);
  static const Color chipGreen = Color(0xFF34C759);
  static const Color chipOrange = Color(0xFFFF9F0A);
  static const Color chipPink = Color(0xFFEF3E88);
  static const Color chipSkyBlue = Color(0xFFCDEEFF);
  static const Color chipMint = Color(0xFFCAFFBA);
  static const Color chipLavender = Color(0xFFF0D3FF);
  static const Color chipSoftGrey = Color(0xFFF4F4F4);
  static const Color chipHotPink = Color(0xFFF25C9A);
  static const Color chipGoldenYellow = Color(0xFFFFE082);
  static const Color chipSlateGray = Color(0xFF6E7279);
  static const Color chipOffWhite = Color(0xFFF9F9F9);
  static const Color dimGrey = Color(0xFF545454);
  static const Color vibrantIndigo = Color(0xFF5E62EF);
  static const Color vibrantIndigo900 = Color(0xFF0D47A1);
  static const Color textSecondary = Color(0xFF757575);
  static const Color textHint = Color(0xFFBDBDBD);
  static const Color tealGreen = Color(0xFF4DB6AC);
  static const Color greyGradientLight = Color(0xFFD3D3D3);
  static const Color greyGradientDark = Color(0xFFC2C1C1);
  static const Color metaliGrey = Color(0xFFABB4BB);
  static const Color pastelRed = Color(0xFFFFB2B2);
  static const Color pastelYellow = Color(0xFFFEF9C2);
  static const Color purpleGradientLight = Color(0xFF5B476A);
  static const Color purpleGradientDark = Color(0xFF8B61AD);
  static const Color softPinkBackground = Color(0xFFFFE4E6);
  static const Color vibrantPink = Color(0xFFFB7185);
  static const Color softTealBackground = Color(0xFFE0FDF4);
  static const Color slateGray = Color(0xFF4B5563);
  static const Color vibrantTeal = Color(0xFF10B981);
}
